---
- name: Install Route53 module
  package:
    name: "{{ le_packages[ansible_os_family][le_plugin] }}"

- name: Enable Route53 module for Letsencrypt
  ini_file:
    path: "{{ le_config_dir }}/cli.ini"
    section: null
    option: "{{ le_plugin }}"
    value: "true"
  run_once: true

- name: Initialize Letsencrypt certificate
  environment:
    AWS_CONFIG_FILE: "{{ le_config_dir }}/aws.ini"
  command: >-
    certbot certonly
    --noninteractive
    --agree-tos
    {% if le_staging_mode %}
    --staging
    {% endif %}
    --{{ le_plugin }}
    --domains {{ le_domains | join(',') | quote }}
  args:
    creates: "{{ le_config_dir }}/live/{{ each_domain }}/fullchain.pem"
  loop: "{{ le_domains }}"
  loop_control:
    loop_var: each_domain
  run_once: true
