---
- name: Install packages
  package:
    name: "{{ le_packages[ansible_os_family].certbot }}"

- name: Configure Letsencrypt CLI
  ini_file:
    path: "{{ le_config_dir }}/cli.ini"
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    noninteractive: "true"
    max-log-backups: 0
    email: "{{ le_email }}"
    agree-tos: "true"
  run_once: true

- name: Configure Letsencrypt deploy hook
  ini_file:
    path: "{{ le_config_dir }}/cli.ini"
    section: null
    option: deploy-hook
    value: "{{ le_deploy_hook }}"
  run_once: true
  when: le_deploy_hook is defined

- name: Set Letsencrypt staging/prod mode
  ini_file:
    path: "{{ le_config_dir }}/cli.ini"
    section: null
    option: "staging"
    value: "true"
    state: "{{ le_staging_mode | ternary('present', 'absent') }}"
  run_once: true
