---
- name: Install packages
  package:
    name: "{{ le_packages[ansible_os_family].certbot }}"

- name: Configure Letsencrypt CLI
  ini_file:
    path: "{{ le_config_dir }}/cli.ini"
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    noninteractive: "true"
    max-log-backups: 0
    email: "{{ le_email }}"
    agree-tos: "true"
  run_once: true

- name: Configure Letsencrypt deploy hook
  ini_file:
    path: "{{ le_config_dir }}/cli.ini"
    section: null
    option: deploy-hook
    value: "{{ le_deploy_hook }}"
  run_once: true
  when: le_deploy_hook is defined

- name: Set Letsencrypt staging/prod mode
  ini_file:
    path: "{{ le_config_dir }}/cli.ini"
    section: null
    option: "staging"
    value: "true"
    state: "{{ le_staging_mode | ternary('present', 'absent') }}"
  run_once: true

- name: Configure Letsencrypt log rotation
  include_role:
    name: devgateway.logrotate
  vars:
    lgrt_name: letsencrypt
    lgrt_path: "{{ le_log_file }}"
    lgrt_config: {}

- name: Include plugin tasks
  include_tasks: "{{ le_plugin }}.yml"

- name: Install Systemd units
  template:
    src: "{{ unit_type }}.j2"
    dest: "{{ le_systemd_dir }}/{{ le_unit_name }}.{{ unit_type }}"
    mode: 0644
  loop:
    - service
    - timer
  loop_control:
    loop_var: unit_type
  register: le_unit_status

- name: Reload Systemd daemon
  command: systemctl daemon-reload
  when: le_unit_status.changed

- name: Enable and start Letsencrypt timer
  service:
    name: "{{ le_unit_name }}.timer"
    enabled: true
    state: started
  when: le_enable_timer
