---
- name: Create webroot directory
  file:
    path: "{{ le_plugin_settings.webroot.directory }}"
    state: directory

- name: Initialize Letsencrypt certificate
  command: >-
    certbot certonly
    --noninteractive
    --agree-tos
    {% if le_staging_mode %}
    --staging
    {% endif %}
    --{{ le_plugin }}
    --webroot-path {{ le_plugin_settings.webroot.directory | quote }}
    --domains {{ le_domains | join(',') | quote }}
  args:
    creates: >-
      {{ '%(path)s/live/%(domain)s/fullchain.pem' | format(
      path = le_config_dir,
      domain = le_domains | first | replace('*.', '')
      ) }}
  run_once: true
